// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "jquery"
import "jquery-ui"
import "bootstrap"
import "custom/menu"
import "custom/courses_subjects"
import "custom/admin_courses"
import "custom/trainee/subject_details"
import "custom/document_upload"
import "custom/trainee_manager"
import "custom/course_subjects_autofill"
import "custom/course_edit"
import "custom/subject_search"
